services:
  # --- MINIO STORAGE ---
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s    
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password      
    command: >
      server /data
      --address "0.0.0.0:9000"
      --console-address "0.0.0.0:9001"         
    networks:
      - veradoc-net
    restart: always

  # --- MINIO BUCKETS SIDECAR ---
  minio-sidecar-buckets:
    image: minio/mc
    container_name: minio-sidecar-buckets
    restart: "no"
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set local http://minio:9000 admin password;
        mc mb --ignore-existing local/custom-corpus;
        mc mb --ignore-existing local/warehouse;
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - veradoc-net        

  # --- MINIO EVENTS SIDECAR ---
  minio-sidecar-events:
    image: minio/mc
    container_name: minio-sidecar-events
    restart: "no"
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for Minio ..."
        until (mc alias set local http://minio:9000 admin password); do 
          echo 'Waiting for MinIO...';
          sleep 1;
        done;

        #echo "Creating buckets..."
        #mc mb --ignore-existing local/custom-corpus;
        #mc mb --ignore-existing local/warehouse;

        echo "Configuring webhooks..."
        mc admin config set local notify_webhook:doc-webhook endpoint='http://veradoc-back:8808/api/v1/document/notification' queue_limit='1000';
        mc admin config set local notify_webhook:metadata-webhook endpoint='http://veradoc-back:8808/api/v1/metadata/notification' queue_limit='1000';

        echo "Restarting Minio server (non-interactive)..."
        mc --json admin service restart local;

        echo "Waiting for Minio to come back online..."
        # Loop until the server responds again
        until (mc admin info local > /dev/null 2>&1); do
          echo "Server restarting...";
          sleep 2;
        done      

        echo "Binding notification webhook to custom corpus bucket"
        mc event add local/custom-corpus arn:minio:sqs::doc-webhook:webhook --event put,delete;

        echo "Binding metadata webhook to warehouse bucket"
        mc event add local/warehouse arn:minio:sqs::metadata-webhook:webhook --event put,delete --prefix 'metadata/' --suffix '.json';
        
        echo "Configuration Complete. Current Events:"
        mc event list local/custom-corpus
        mc event list local/warehouse        
    depends_on:
      veradoc-back:
          condition: service_healthy    
    networks:
      - veradoc-net

  # --- AGENTIC AI SERVICE ---
  veradoc-back:
    image: veradocai/veradoc-back
    container_name: veradoc-back
    environment:
      - APP_ENV=prod
    ports:
      - "8808:8808"
    # Shared memory is important for PyTorch/Numpy heavy workloads
    shm_size: '2gb'
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://veradoc-back:8808/health')\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s          
    depends_on:
      minio-sidecar-buckets:
        condition: service_completed_successfully      
      ollama:
        condition: service_healthy
    networks:
      - veradoc-net

  # --- APP UI SERVICE ---
  veradoc-ui:
    image: veradocai/veradoc-ui
    container_name: veradoc-ui
    ports:
      - "4200:80"
    depends_on:
      - veradoc-back      
    networks:
      - veradoc-net
    restart: always  

volumes:
  minio-data:
    name: minio-data

networks:
  veradoc-net: 
    name: veradoc-net